# yazi theme — generated by Omarchy from the active theme's colors.toml.
# Color placeholders are filled in on every `omarchy-theme-set`.
# DO NOT edit the generated copy in current/theme/ — edit this .tpl (managed via chezmoi).

[mgr]
cwd = { fg = "{{ color6 }}" }

# Hovered
hovered         = { fg = "{{ background }}", bg = "{{ accent }}" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "{{ color3 }}", italic = true }
find_position = { fg = "{{ color5 }}", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "{{ color2 }}", bg = "{{ color2 }}" }
marker_cut      = { fg = "{{ color1 }}", bg = "{{ color1 }}" }
marker_marked   = { fg = "{{ color6 }}", bg = "{{ color6 }}" }
marker_selected = { fg = "{{ color3 }}", bg = "{{ color3 }}" }

# Tab
tab_active   = { fg = "{{ background }}", bg = "{{ accent }}" }
tab_inactive = { fg = "{{ foreground }}", bg = "{{ color0 }}" }
tab_width    = 1

# Count
count_copied   = { fg = "{{ background }}", bg = "{{ color2 }}" }
count_cut      = { fg = "{{ background }}", bg = "{{ color1 }}" }
count_selected = { fg = "{{ background }}", bg = "{{ color3 }}" }

# Border
border_symbol = "│"
border_style  = { fg = "{{ color8 }}" }

[mode]
normal_main = { fg = "{{ background }}", bg = "{{ accent }}", bold = true }
normal_alt  = { fg = "{{ accent }}", bg = "{{ color0 }}" }
select_main = { fg = "{{ background }}", bg = "{{ color2 }}", bold = true }
select_alt  = { fg = "{{ color2 }}", bg = "{{ color0 }}" }
unset_main  = { fg = "{{ background }}", bg = "{{ color5 }}", bold = true }
unset_alt   = { fg = "{{ color5 }}", bg = "{{ color0 }}" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "{{ color0 }}", bg = "{{ color0 }}" }

# Progress
progress_label  = { fg = "{{ foreground }}", bold = true }
progress_normal = { fg = "{{ accent }}", bg = "{{ color0 }}" }
progress_error  = { fg = "{{ color1 }}", bg = "{{ color0 }}" }

# Permissions
perm_type  = { fg = "{{ accent }}" }
perm_read  = { fg = "{{ color3 }}" }
perm_write = { fg = "{{ color1 }}" }
perm_exec  = { fg = "{{ color2 }}" }
perm_sep   = { fg = "{{ color8 }}" }

[pick]
border   = { fg = "{{ accent }}" }
active   = { fg = "{{ color5 }}", bold = true }
inactive = {}

[input]
border   = { fg = "{{ accent }}" }
title    = {}
value    = {}
selected = { reversed = true }

[cmp]
border = { fg = "{{ accent }}" }

[tasks]
border  = { fg = "{{ accent }}" }
title   = {}
hovered = { fg = "{{ color5 }}", underline = true }

[which]
mask            = { bg = "{{ color0 }}" }
cand            = { fg = "{{ color6 }}" }
rest            = { fg = "{{ color8 }}" }
desc            = { fg = "{{ color5 }}" }
separator       = "  "
separator_style = { fg = "{{ color0 }}" }

[notify]
title_info  = { fg = "{{ color2 }}" }
title_warn  = { fg = "{{ color3 }}" }
title_error = { fg = "{{ color1 }}" }

[filetype]
rules = [
  { mime = "image/*",                                 fg = "{{ color6 }}" },
  { mime = "{audio,video}/*",                         fg = "{{ color3 }}" },
  { mime = "application/{,g}zip",                     fg = "{{ color5 }}" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "{{ color5 }}" },
  { mime = "application/{pdf,doc,rtf}",               fg = "{{ accent }}" },

  { url = "*", is = "orphan", fg = "{{ color1 }}" },
  { url = "*", is = "exec",   fg = "{{ color2 }}" },
  { url = "*/",               fg = "{{ accent }}" },
]
